### ISSUE TITLE
Falsches format

### ISSUE THREAD

**Issue by wernerlat** [serWm/Lieferscheine#3]
Bei Hoher Anzahl eines Artikels wird ein Formfehler ausgegeben in Verbindung mit der EinheitEntfernen Funktion in der Database Klasse (Datei heißt noch Data). Muss irgendwas mit der länge des strings und dem enthaltenden Komma zutun haben.

**Comment by y0sh1DE** [comment]
Konnte jetzt nichts machen weil ich den OLEDB Treiber nicht installiert hab.

Kann morgen mal drauf gucken wenn ich von der Arbeit komme und der Issue noch offen ist.

**Comment by wernerlat** [comment]
es war ein dreck

**Comment by wernerlat** [comment]
Ja moin lesen hilft es war ein drecks + "€"
